INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("Status","??","Single, Married/Joint, Head_of_House, Married/Sep, Widow(er)",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("Under65?","Yes","Age at end of 2011. (Yes/No) If Married/Joint, Y=both-under, N=both-over, 1=One-over",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("Dependents","??","Number of Dependents, self=1, spouse, etc.",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L7","??","Wages, salaries, tips (W-2's Box-1).",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L8a","??","Interest 1099-INT",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L9","0","Ordinary Dividends 1099-DIV (1a)",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L9b","0","Qualified Dividends 1099-DIV (1b)",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L10",";","Taxable refunds.",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L11",";","Alimony received.",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L12",";","Business income/loss. (Sched C)",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("Cap-Gains-A","","Capital Gains/Losses, 1099-B.  For which Basis Reported to IRS (Form 8949 check-A)",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("Cap-Gains-B","","Capital Gains/Losses, 1099-B.  For which Basis NOT Reported to IRS (Form 8949 check-B)",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("Cap-Gains-C","","Capital Gains/Losses, 1099-B.  For which Form 8949 (A)+(B) can NOT be checked. (check-C)",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("D4",";","Short-term gain from 6252, gain or loss from Forms 4684, 6781, 8824.",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("D5",";","Short-term gain/loss from partnerships, S corps, estates, trusts, K-1.",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("D6",";","Short-term 2010 loss carryover. Or, LastYear's return output File-name.",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("D11",";","Gain from Form 4797.",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("D12",";","Partnership net long-term gains or losses.",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("D13",";","Cap Gains Distributions - 1099-DIV column 2a.",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("D14",";","Long-term 2010 loss carryover. Leave blank if file-name used in line D6.",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L14",";","Other gains or losses. (form 4797)",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L15b",";","Taxable IRA distributions (pg 23)",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L16b",";","Taxable Pensions/annuities (pg 24)",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L17",";","Rent realestate/royalties/partnerships/S corp. Sched E",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L18",";","Farm income/loss. (Sched F)",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L19",";","Unemployment compensation",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L20b",";","Taxable Social security benefits",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L21",";","Other income. (pg 28)",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L23",";","Educator expenses",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L24",";","Bus. exp.: reservists, artists, ... Attach Form 2106",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L25",";","Health savings account deduction. Attach Form 8889",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L26",";","Moving expenses. Attach Form 3903",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L27",";","One-half of self-employment tax. Attach Schedule SE",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L28",";","Self-employed SEP, SIMPLE, and qualified plans",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L29",";","Self-employed health insurance deduction",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L30",";","Penalty on early withdrawal of savings",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L31a",";","Alimony paid",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L32",";","IRA deduction",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L33",";","Student loan interest deduction",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L34",";","Tuition and fees deduction. Attach Form 8917",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L35",";","Domestic production activities deduction, Form 8903",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L39",";","Number of boxes checked (0-4), line-39:  You, Spouse : >65, blind.",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("Collectibles",";","Gains or Losses from Collectibles. (Usually zero.)",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("A1",";","Unreimbursed medical expenses.",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("A5","0 ;","State and local income taxes. (W-2's box 19.)",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("A6","0 ;","Real estate taxes.",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("A7",";","New motor vehicle taxes.",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("A8",";","Other taxes.",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("A10",";","Home mortgage interest and points",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("A11",";","Home mortgage interest not reported to you on Form 1098.",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("A12",";","Points not reported to you on Form 1098.",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("A13",";","Qualified mortgage insurance premium.",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("A14",";","Investment interest. Attach Form 4952",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("A16","0 ;","Charity contributions.",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("A17",";","Contributions other than cash or check.",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("A18",";","Carryover from prior year",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("A20",";","Casualty or theft loss(es).",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("A21",";","Unreimbursed employee expenses",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("A22",";","Tax preparation fees",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("A23",";","Other expenses",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("A28",";","Other deductions, listed on Sched-A page A-6.",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L47",";","Foreign tax credit, form 1116",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L48",";","Child/dependent care expense credits. Form 2441.",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L49",";","Education credits. Form 8863",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L50",";","Retirement savings contributions credit. Form 8880.",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L51",";","Child tax credit (see page 42).",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L52",";","Residential energy credits. Form 5695.",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L53",";","Other credits. Forms 3800, 8801, etc.",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L56",";","Self-employment tax. Sched SE",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L57",";","Unreported social security and Medicare tax from Form 4137",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L58",";","Additional tax on IRAs, other qualified retirement plans, Form 5329",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L59a",";","Household employment taxes. Sched H",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L59b",";","First-time homebuyer credit repayment. Form 5405.",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L60",";","Other taxes.",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L62","??","Federal income tax witheld, from W-2's, box-2",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L63",";","2011 estimated payments + amnt applied from 2010",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L64a",";","Earned income credit (EIC)",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L65",";","Additional child tax credit. Attach Form 8812",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L66",";","American opportunity credit. Form 8863, line 14.",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L67",";","First-time homebuyer credit, Form 5405, line 10.",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L68",";","Amnt paid in filing extension req.",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L69",";","Excess soc. sec. + tier1 RRTA tax withheld",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L70",";","Credits for federal tax on fuels. Attach form 4136",2011);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year) VALUES("L71",";","Credits from Form 2439, 4136, 6801, 8885",2011);
