script/generate scaffold station  dtv:string antennatype:string call_sign:string channel:float network:string city__state:string livedate:string compassheading:string milesfrom:float rfchannel:integer
script/generate scaffold huelshow  name:string shortname:string id:integer
script/generate scaffold network  nmap_addresses:string last_scan:datetime expanded:boolean nmap_execution_time:float id:integer
script/generate scaffold huelserie  show:string name:string id:integer number:integer
script/generate scaffold example_type  import_class:string example_string:string id:integer inspect_value:string
exit
script/generate scaffold router  id:integer Model:string Version:float Serial_Number:string WAN_MAC:string Status:string Power_Supply:string created_at:datetime updated_at:datetime
script/generate scaffold measurements  description:string load_measurement:string load:float power_factor:float period:string duty_cycle_measurement:string duty_cycle:float load_id:integer mode:string va:float
script/generate scaffold breakers  node:integer description:string parent_node:integer parent_description:string volts:integer amps:integer measured_load:integer id:integer Position:integer
script/generate scaffold wired_location  id:integer description:string plug_in_location:integer x10_address:string room:string wall:string type:string ground_test_light:integer
script/generate scaffold nodes  node:integer description:string parent_node:integer parent_description:string id:integer
script/generate scaffold table_specs  model_class_name:string min_seconds:float max_seconds:float scheduled_time:datetime id:integer merge:string file_caching:string interval:float shortest_update:float longest_no_update:float
script/generate scaffold acquisition_stream_spec  id:integer acquisition_interface:string url:string table_spec_id:integer required_order:integer
script/generate scaffold parse_spec  parse_interface:string table_selection:string row_selection:string name_prefix:string column_name_location:string column_name_selection:string column_selection:string column_value_selection:string table_selection_is_regexp:boolean acquisition_stream_spec_id:integer id:integer
script/generate scaffold acquisition  acquisition_data:string created_at:datetime id:integer url:string acquisition_stream_id:integer error:string acquisition_updated:boolean
script/generate scaffold host  nmap:text otherports:integer otherstate:string mac:string nicvendor:string ip:string name:string last_detection:datetime nmap_execution_time:float id:integer
exit
script/generate scaffold assembly_specs  model_class:string parse_stream_id:integer
script/generate scaffold productions  id:integer power:float created_at:datetime updated_at:datetime
script/generate scaffold production_ftp  timestamp:time backup_state:integer co2_saved:float error:integer e_total:float fac:float grid_type:integer h_on:float h_total:float iac:float ipv:float mode:integer pac:float power_on:integer serial_number:integer temperature:float vac:float vpv:float Date:date
script/generate scaffold edison  CANUM:string SANUM:string READDATE:date KHWREAD:integer kwhusage:float Days:integer AVGDAILY:float TOTCHARGES:decimal
script/generate scaffold loads1nf  wired_location:integer loads_description:string x_10_address:string volatile:boolean load_measurement:string load:integer power_factor:string period:string duty_cycle_measurement:string duty_cycle:string load_id:integer daylight_savings_adjustment:boolean tmer_savings:boolean motion_savings:boolean bedtime_savings:boolean away_savings:boolean background:boolean computer_common:boolean audio_video:boolean recorder:boolean wired_location_description:string room:string wall:string type:string ground_test_light:boolean location_id:integer breaker:integer new_breaker:integer volts:integer phase:string amps:integer measured_load:integer label:string va:float plug_width:float mode:string id:integer x10_address:string plug_in_location:integer
script/generate scaffold loads1  wired_location:integer description:string x_10_address:string volatile:integer mode:string load_measurement:string load:integer va:string power_factor:float period:string duty_cycle_measurement:string duty_cycle:float load_id:integer daylight_savings_adjustment:integer tmer_savings:integer motion_savings:integer bedtime_savings:integer away_savings:integer background:integer computer_common:integer audio_video:integer recorder:integer plug_width:string
script/generate scaffold postgresql2rails  postgresql_type:string rails_type:string
script/generate scaffold loads_scaffold  id:integer node:integer description:string parent_node:integer parent_description:string plug_in_location:integer x_10_address:string volatile:boolean daylight_savings_adjustment:boolean timer_savings:boolean motion_savings:boolean bedtime_savings:boolean away_savings:boolean background:boolean computer_common:boolean audio_video:boolean recorder:boolean plug_width:string created_at:datetime updated_at:datetime
script/generate scaffold postgresql2import  postgresql_type:string import_type:string
script/generate scaffold parameters  id:integer parameter:string import_type:string value:string formula:string created_at:datetime updated_at:datetime
script/generate scaffold params  id:integer parameter:string import_type:string value:string formula:string created_at:datetime updated_at:datetime
script/generate scaffold generic_columns  id:integer model_class:string Column_Name:string Before_Pattern:string Data_Pattern:string After_Pattern:string created_at:datetime updated_at:datetime
script/generate scaffold transactions  id:integer Date:datetime Posted:datetime Payee:string Descrition:string From_Accont:string To_Account:string Amount:float Tax_Reporting:string created_at:datetime updated_at:datetime
script/generate scaffold ted_web_box_fulls  id:integer hour:integer minute:integer month:integer day:integer year:integer maxsecond:integer accusecond:integer total_voltagenow:integer mtu1_voltagenow:integer total_powernow:integer total_kva:integer mtu1_powernow:integer mtu1_kva:integer total_costnow:integer mtu1_costnow:integer created_at:datetime updated_at:datetime sign:boolean outlier:integer production:float prediction:float predictkva:float switched_state:integer noise:float prediction_samples:integer change_interval:float switched_age:float predict_reactive_power:float backup_state:string co2_saved_lbs:float error:string e_total_kwh:float event_cnt:integer fac_hz:float grid_type:string h_on_h:float h_total_h:float iac_a:integer i_dif_ma:integer ipv_a:integer max_temperature_degc:float max_vpv_v:integer mode:string pac_w:integer power_on:integer serial_number:integer temperature_degc:float vac_v:float vacl1_v:float vacl2_v:float vfan_v:integer vpv__pe_v:integer vpv_v:integer vpv_setpoint_v:integer prefix:string
script/generate scaffold example_acquisitions  id:integer acquisition_data:string acquisition_id:integer
script/generate scaffold generic_acquisitions  id:integer model_class:string acquisition_interface:string url:string table_selection:string row_selection:string created_at:datetime updated_at:datetime parse_interface:string tree_walk:string name_prefix:string column_name_location:string column_name_selection:string column_selection:string column_value_selection:string table_selection_is_regexp:boolean min_seconds:float max_seconds:float acquisition_size:string file_caching:string
script/generate scaffold generic_types  search_sequence:integer import_class:string rails_type:string data_regexp:string id:integer ruby_conversion:string
