insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('account','','unit','',2,4372,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('accounts','','functional','',7,10,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquire_all_observer','','unit','',1,1,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition','','unit','',5,3502,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisitions','','functional','',7,9,0,1);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_interface','','unit','',5,62,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_interfaces','','functional','',7,10,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_stream_spec','','unit','',12,7437,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_stream_specs','','functional','',7,10,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('breaker','','unit','',1,1,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('breakers','','functional','',7,10,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('bug','','unit','',1,1,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('bugs','','functional','',7,0,0,7);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('edison','','unit','',1,1,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('edisons','','functional','',7,8,0,1);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('error_type','','unit','',1,1,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('error_types','','functional','',7,10,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('example_type','','unit','',1,1,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('example_types','','functional','',7,10,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('frequency','','unit','',4,1021,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('frequencies','','functional','',7,10,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('generic_table','','unit','',4,126,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('generic_type','','unit','',1,1,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('generic_types','','functional','',7,10,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('global','','unit','',8,33,1,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('host','','unit','',1,1,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('hosts','','functional','',7,10,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('huelserie','','unit','',1,1,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('huelseries','','functional','',7,0,0,7);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('huelshow','','unit','',1,1,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('huelshows','','functional','',7,10,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('loads','','functional','',7,9,1,1);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('loads','','unit','',1,1,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('loads1','','unit','',1,1,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('measurement','','unit','',1,1,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('measurements','','functional','',7,10,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('node','','unit','',1,1,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('nodes','','functional','',7,10,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('parse_spec','','unit','',1,1,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('parse_specs','','functional','',7,10,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('production','','unit','',1,1,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('productions','','functional','',7,10,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('production_ftp','','unit','',1,1,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('production_ftps','','functional','',7,10,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('router','','unit','',1,1,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('routers','','functional','',7,10,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('table_spec','','unit','',6,4222,0,1);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('table_specs','','functional','',7,10,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('tedprimary','','unit','',1,1,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('tedprimaries','','functional','',7,10,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('transaction','','unit','',1,1,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('transfer','','unit','',9,23750,3,2);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('transfers','','functional','',7,4734,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('url','','unit','',1,1,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('urls','','functional','',7,6,0,4);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('weather','','unit','',1,1,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('weathers','','functional','',7,10,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('wired_location','','unit','',1,1,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('wired_locations','','functional','',7,10,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_interface','','unit','',5,62,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('test_run','','unit','',1,1,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('test_runs','','functional','',7,0,0,7);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('test_runs','','functional','',7,0,0,7);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('test_runs','','functional','',7,10,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_interfaces','','functional','',7,10,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_interfaces','','functional','',7,0,0,7);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_interfaces','','functional','',7,0,0,7);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_interfaces','','functional','',7,0,0,7);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_interfaces','','functional','',7,0,0,7);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_interfaces','','functional','',7,0,0,7);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_interfaces','','functional','',7,3,0,5);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_interfaces','','functional','',7,5,0,4);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_interfaces','','functional','',7,5,0,4);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_interfaces','','functional','',7,8,0,2);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_interfaces','','functional','',7,9,0,1);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_interfaces','','functional','',7,10,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_interface','','unit','',5,50,0,1);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_interfaces','','functional','',7,10,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_interface','','unit','',5,1,0,5);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_interfaces','','functional','',7,0,0,7);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_interface','','unit','',5,50,0,1);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_interfaces','','functional','',7,10,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_interface','','unit','',5,52,0,1);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_interfaces','','functional','',7,10,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_interface','','unit','',5,62,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',1,1,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',1,1,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_interface','','unit','',5,62,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_interface','','unit','',5,62,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_interface','','unit','',5,34,2,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_interface','','unit','',5,57,1,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_interface','','unit','',5,61,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_interface','','unit','',5,62,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',1,1,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',1,0,0,1);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',1,0,0,1);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',1,1,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_interface','','unit','',5,22,0,2);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_interface','','unit','',5,34,0,1);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_interface','','unit','',5,62,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_interface','','unit','',5,62,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_interface','','unit','',5,25,1,1);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_interface','','unit','',5,25,0,2);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_interface','','unit','',5,45,1,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',1,1,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',1,1,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',2,72,0,2);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_interface','','unit','',5,45,1,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',2,72,0,2);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('acquisition_interface','','unit','',5,45,1,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',2,72,0,2);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',2,72,0,2);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',2,722,2,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',2,722,2,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',2,722,2,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',2,720,0,2);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',2,722,2,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',2,722,2,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',2,12,0,2);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',2,722,0,2);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',2,722,2,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',2,1061,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',2,2,0,2);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',2,2,0,2);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',2,1061,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',2,1061,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',3,1428,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',3,1429,1,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',3,1429,1,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',3,1445,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',3,1443,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',3,1443,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',3,1443,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',3,1443,0,1);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',3,1443,0,1);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',3,1429,0,1);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',3,1451,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',3,1428,0,1);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',3,1451,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',3,1451,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',3,1451,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',3,1451,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error) values('ruby_interface','','unit','',3,1451,0,0);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error,created_at,updated_at) values('ruby_interface','','unit','',3,1451,0,0,Wed Jun 01 20:42:18 -0700 2011,Wed Jun 01 20:42:18 -0700 2011);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error,created_at,updated_at) values('ruby_interfaces','','functional','',7,0,0,7,Wed Jun 01 20:42:43 -0700 2011,Wed Jun 01 20:42:43 -0700 2011);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error,created_at,updated_at) values('ruby_interfaces','','functional','',7,11,1,0,Wed Jun 01 20:45:51 -0700 2011,Wed Jun 01 20:45:51 -0700 2011);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error,created_at,updated_at) values('ruby_interfaces','','functional','',7,10,0,0,Wed Jun 01 20:47:52 -0700 2011,Wed Jun 01 20:47:52 -0700 2011);
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error,created_at,updated_at) values('ruby_interfaces','','functional','',7,10,0,0,'Wed Jun 01 21:19:16 -0700 2011','Wed Jun 01 21:19:16 -0700 2011');
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error,created_at,updated_at) values('acquisition_interface','','unit','',5,34,2,0,'Thu, 02 Jun 2011 00:53:47 -0700','Thu, 02 Jun 2011 00:53:47 -0700');
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error,created_at,updated_at) values('acquisition_interface','','unit','',5,36,2,0,'Thu, 02 Jun 2011 00:57:32 -0700','Thu, 02 Jun 2011 00:57:32 -0700');
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error,created_at,updated_at) values('acquisition_interface','','unit','',5,45,1,0,'Thu, 02 Jun 2011 00:59:17 -0700','Thu, 02 Jun 2011 00:59:17 -0700');
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error,created_at,updated_at) values('acquisition_interface','','unit','',5,45,1,0,'Thu, 02 Jun 2011 07:53:46 -0700','Thu, 02 Jun 2011 07:53:46 -0700');
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error,created_at,updated_at) values('acquisition_interface','','unit','',5,45,1,0,'Fri, 03 Jun 2011 15:02:41 -0700','Fri, 03 Jun 2011 15:02:41 -0700');
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error,created_at,updated_at) values('acquisition_interface','','unit','',5,45,1,0,'Sat, 04 Jun 2011 16:19:06 -0700','Sat, 04 Jun 2011 16:19:06 -0700');
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error,created_at,updated_at) values('ruby_interfaces','','functional','',7,10,0,0,'Sat, 04 Jun 2011 16:19:49 -0700','Sat, 04 Jun 2011 16:19:49 -0700');
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error,created_at,updated_at) values('acquisition_interfaces','','functional','',7,10,0,0,'Sat, 04 Jun 2011 16:20:47 -0700','Sat, 04 Jun 2011 16:20:47 -0700');
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error,created_at,updated_at) values('acquisition_interfaces','','functional','',7,10,0,0,'Sat, 04 Jun 2011 16:25:10 -0700','Sat, 04 Jun 2011 16:25:10 -0700');
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error,created_at,updated_at) values('ruby_interfaces','','functional','',7,10,0,0,'Sat, 04 Jun 2011 16:25:44 -0700','Sat, 04 Jun 2011 16:25:44 -0700');
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error,created_at,updated_at) values('ruby_interfaces','','functional','',7,9,0,1,'Sat, 04 Jun 2011 16:34:48 -0700','Sat, 04 Jun 2011 16:34:48 -0700');
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error,created_at,updated_at) values('ruby_interfaces','','functional','',7,10,0,0,'Sat, 04 Jun 2011 16:36:04 -0700','Sat, 04 Jun 2011 16:36:04 -0700');
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error,created_at,updated_at) values('ruby_interfaces','','functional','',7,8,0,2,'Sat, 04 Jun 2011 16:37:59 -0700','Sat, 04 Jun 2011 16:37:59 -0700');
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error,created_at,updated_at) values('ruby_interfaces','','functional','',7,10,0,0,'Sat, 04 Jun 2011 16:38:49 -0700','Sat, 04 Jun 2011 16:38:49 -0700');
insert into test_runs(model,test,test_type,environment,tests,assertions,failures,tests_stop_on_error,created_at,updated_at) values('acquisition_interfaces','','functional','',7,10,0,0,'Sat, 04 Jun 2011 16:39:21 -0700','Sat, 04 Jun 2011 16:39:21 -0700');
