INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES(NULL,NULL,NULL,2012,1);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES(NULL,NULL,NULL,2012,2);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES(NULL,NULL,NULL,2012,3);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES(NULL,NULL,NULL,2012,4);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("Status","??","Single, Married/Joint, Head_of_House, Married/Sep, Widow(er)",2012,5);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES(NULL,NULL,NULL,2012,6);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("Under65?","Yes","Age at end of 2012. (Yes/No) If Married/Joint, Y=both-under, N=both-over, 1=One-over",2012,7);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES(NULL,NULL,NULL,2012,8);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("Dependents","??","Number of Dependents, self=1, spouse, etc.",2012,9);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES(NULL,NULL,NULL,2012,10);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES(NULL,NULL,NULL,2012,11);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L7","??","Wages, salaries, tips (W-2's Box-1).",2012,12);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES(NULL,NULL,NULL,2012,13);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L8a","??","Interest 1099-INT.  Place these numbers on Schedule-B, Part I.",2012,14);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES(NULL,NULL,NULL,2012,15);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L9","0","Ordinary Dividends 1099-DIV (1a).  Place these numbers on Schedule-B, Part II.",2012,16);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES(NULL,NULL,NULL,2012,17);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L9b","0","Qualified Dividends 1099-DIV (1b)",2012,18);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES(NULL,NULL,NULL,2012,19);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L10",";","Taxable refunds.",2012,20);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L11",";","Alimony received.",2012,21);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L12",";","Business income/loss. (Sched C)",2012,22);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("Cap-Gains-A","","Capital Gains/Losses, 1099-B.  For which Basis Reported to IRS (Form 8949 check-A)",2012,23);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES(NULL,NULL,NULL,2012,24);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES(NULL,NULL,NULL,2012,25);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("Cap-Gains-B","","Capital Gains/Losses, 1099-B.  For which Basis NOT Reported to IRS (Form 8949 check-B)",2012,26);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES(NULL,NULL,NULL,2012,27);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES(NULL,NULL,NULL,2012,28);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("Cap-Gains-C","","Capital Gains/Losses, 1099-B.  For which Form 8949 (A)+(B) can NOT be checked. (check-C)",2012,29);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES(NULL,NULL,NULL,2012,30);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES(NULL,NULL,NULL,2012,31);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES(NULL,NULL,NULL,2012,32);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("D4",";","Short-term gain from 6252, gain or loss from Forms 4684, 6781, 8824.",2012,33);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("D5",";","Short-term gain/loss from partnerships, S corps, estates, trusts, K-1.",2012,34);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("D6",";","Short-term 2011 loss carryover. Or, LastYear's return output File-name.",2012,35);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("D11",";","Gain from Form 4797.",2012,36);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("D12",";","Partnership net long-term gains or losses.",2012,37);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("D13",";","Cap Gains Distributions - 1099-DIV column 2a.",2012,38);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("D14",";","Long-term 2011 loss carryover. Leave blank if file-name used in line D6.",2012,39);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L14",";","Other gains or losses. (form 4797)",2012,40);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L15b",";","Taxable IRA distributions (pg 23)",2012,41);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L16b",";","Taxable Pensions/annuities (pg 24)",2012,42);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L17",";","Rent realestate/royalties/partnerships/S corp. Sched E",2012,43);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L18",";","Farm income/loss. (Sched F)",2012,44);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L19",";","Unemployment compensation",2012,45);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L20b",";","Taxable Social security benefits",2012,46);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L21",";","Other income. (pg 28)",2012,47);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES(NULL,NULL,NULL,2012,48);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES(NULL,NULL,NULL,2012,49);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L24",";","Bus. exp.: reservists, artists, ... Attach Form 2106",2012,50);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L25",";","Health savings account deduction. Attach Form 8889",2012,51);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L26",";","Moving expenses. Attach Form 3903",2012,52);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L27",";","Deductable part of self-employment tax. Attach Schedule SE",2012,53);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L28",";","Self-employed SEP, SIMPLE, and qualified plans",2012,54);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L29",";","Self-employed health insurance deduction",2012,55);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L30",";","Penalty on early withdrawal of savings",2012,56);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L31a",";","Alimony paid",2012,57);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L32",";","IRA deduction",2012,58);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L33",";","Student loan interest deduction",2012,59);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L35",";","Domestic production activities deduction, Form 8903",2012,60);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L39",";","Number of boxes checked (0-4), line-39:  You, Spouse : >65, blind.",2012,61);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES(NULL,NULL,NULL,2012,62);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("Collectibles",";","Gains or Losses from Collectibles. (Usually zero.)",2012,63);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES(NULL,NULL,NULL,2012,64);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES(NULL,NULL,NULL,2012,65);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES(NULL,NULL,NULL,2012,66);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("A1",";","Unreimbursed medical expenses.",2012,67);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("A5","0 ;","State and local income taxes. (W-2's box 19.)",2012,68);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("A6","0 ;","Real estate taxes.",2012,69);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("A7",";","Personal property taxes.",2012,70);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("A8",";","Other taxes.",2012,71);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("A10",";","Home mortgage interest and points",2012,72);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("A11",";","Home mortgage interest not reported to you on Form 1098.",2012,73);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("A12",";","Points not reported to you on Form 1098.",2012,74);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("A14",";","Investment interest. Attach Form 4952",2012,75);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("A16","0 ;","Charity contributions.",2012,76);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("A17",";","Contributions other than cash or check.",2012,77);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("A18",";","Carryover from prior year",2012,78);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("A20",";","Casualty or theft loss(es).",2012,79);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("A21",";","Unreimbursed employee expenses",2012,80);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("A22",";","Tax preparation fees",2012,81);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("A23",";","Other expenses",2012,82);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("A28",";","Other deductions, listed on Sched-A page A-6.",2012,83);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES(NULL,NULL,NULL,2012,84);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L47",";","Foreign tax credit, form 1116",2012,85);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L48",";","Child/dependent care expense credits. Form 2441.",2012,86);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L49",";","Education credits. Form 8863, line 19.",2012,87);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L50",";","Retirement savings contributions credit. Form 8880.",2012,88);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L51",";","Child tax credit (Sched 8812).",2012,89);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L52",";","Residential energy credits. Form 5695.",2012,90);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L53",";","Other credits. Forms 3800, 8801, etc.",2012,91);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES(NULL,NULL,NULL,2012,92);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES(NULL,NULL,NULL,2012,93);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L56",";","Self-employment tax. Sched SE",2012,94);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L57",";","Unreported social security and Medicare tax from Form 4137, 8919",2012,95);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L58",";","Additional tax on IRAs, other qualified retirement plans, Form 5329",2012,96);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L59a",";","Household employment taxes. Sched H",2012,97);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L59b",";","First-time homebuyer credit repayment. Form 5405.",2012,98);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L60",";","Other taxes.",2012,99);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES(NULL,NULL,NULL,2012,100);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES(NULL,NULL,NULL,2012,101);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L62","??","Federal income tax witheld, from W-2's, box-2",2012,102);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES(NULL,NULL,NULL,2012,103);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L63",";","2012 estimated payments + amnt applied from 2011",2012,104);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L64a",";","Earned income credit (EIC)",2012,105);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L65",";","Additional child tax credit. Attach Form 8812",2012,106);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L66",";","American opportunity credit. Form 8863, line 8.",2012,107);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L68",";","Amnt paid in filing extension req.",2012,108);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L69",";","Excess soc. sec. + tier1 RRTA tax withheld",2012,109);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L70",";","Credits for federal tax on fuels. Attach form 4136",2012,110);
INSERT INTO open_tax_solvers(name,type_chars,description,tax_year,id) VALUES("L71",";","Credits from Form 2439, 4136, 6801, 8885",2012,111);
